
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1ESXlOakE0TXpVek9Gb1hEVE16TURJeU16QTRNelV6T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjVtCjBvY0JhYkMraHg3V1JrMC9CSmlYTUdoTE95Uzc0dWwxZ2VxZjFiNDJvMUtGNzVJdGFUZUxLN1VEUjVqVXNOQVkKTktha0QrSURmaVRDallmNUU1VlZJMzVJRTRTeEJBNVFiV3VsbVVrbnhjTENubTdQOFlXVlovWUNMWGVCdDVXSgpzdVN5cEEzTHROTGc1cCtOWkVGMnVuYkFidkowWldrdjljNFo2UUhSd1NLN2dMMDBXMzVpN2VJZVc3dEl3UDBQCm1kQUJxN054d0EvSXJqUFVpY0tFNjRMMm5sVGJxaFdIMEd3M3l5Y1c5amZNb3UyMnI5TFAzRmNZbldtTS80ODAKV1Z6RGk5MlpCN2lsV2s2ajJPYVRnQ3hRM0IxcGVFMjh0TytkdzFwb0lxdWxBZGs0QWlYYW1TUWhmMHVzcGpwcwpMVmxrNHpvdU94VlQ1YitBTmtVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMRlRJV1JCSU41UnFSRlQvRVl6MUt1RnlnTzJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTUhQNmdlZ1ZETkd2ZVZzUlZ0aApUbmJ0UjAxaThGRzlMaVhiWmNnMWk3QmhpeEw4dFJVTjg1c2w3bnFmWmZLSHF2elNDeVFzeHRzNVlXQmtnSHVjCk5weVI4SXpXa2tPZFRlcEc2U09HazJ1T2dCdU5kSE9RSTFrYThQL1V4WnVSSUJUMmZoQTRmVVZyclEvMVFzMEgKZ0tZZHU3T00xZXFZNjF6NHdLU3FRMTh5K1lNSGIzMnF0Ymo3NlBqYmtqaGhnUCtDaGtoRFN4VmpTcHJ1SnRrSgoxczNSbENncEZpdzRPTVNtTktqUDIvQTJ4SU5YeHRCZWdyZ0pZRUNzeEhLeXJYM1VCQ1AxeVhRbFFxa3RKSE93CjV3KzRGcFZkVVNKZDJjeDdZb01EQlZJM0M2RnFGR0lrNmxoUVdOUkpTMHdXQXVkdmJnS1gvQytwOTBUZzgvQy8KUGc4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://9651bbc7-672f-4ce7-8d9c-fbd6b970667f.ap-south-1.linodelke.net:443
  name: lke94929

users:
- name: lke94929-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZtYkpLcXBLLWJ5MkQyV2pTMEJlOXBGU1dTVlM5U0pvUnd4bFZPNFB0YTAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4teHp2dGIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDRhZjliYmEtNTI0Yi00MmM2LTg0OGQtMTYzN2NjYmUzOGQyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.rgzazYaHmWAJVtjZIk7XjH_RaZySyA9lCNhUsP6md2t_Lcv2Gvb2JI2i0zGX7PzPU0ImY_-fwzsZKCsGVu2riiKNr3KSWidSiq-HnR06qtHY3qYp2kekxd0MJAOBi6OFcIDrJ1oJNi9OLaqm8UzfoIG60ECij_KcciYD1o5A4gBi6iiuyk-tJ1lsxzFal4ZYC86FXpzH2J3Je65uqC9d0VoShBA7j6TwU9-hhIwnC19G66rqGlFdgEXoBVs1Tnd0O8FjfiRw3hI5dANy03RgTyOPzJyYJXfoYrAEAOIZECwJsSJapdPg16EMRhPuMhm_Wj_cJAvyDEnONXMpzQpAWg

contexts:
- context:
    cluster: lke94929
    namespace: default
    user: lke94929-admin
  name: lke94929-ctx

current-context: lke94929-ctx
